LogLevel ERROR
StrictHostKeyChecking no
UserKnownHostsFile /dev/null

Host 10.0.1.12
  HostName 127.0.0.1
  Port 2201
  User lab
  IdentityFile ~/.ssh/termstead-lab
  RequestTTY force
  RemoteCommand sh /tmp/demo/web01.sh

Host stage.internal
  HostName app
  Port 22
  User lab
  IdentityFile ~/.ssh/termstead-lab
  RequestTTY force
  RemoteCommand sh /tmp/demo/staging.sh

Host bastion-01
  HostName 127.0.0.1
  Port 2202
  User lab
  IdentityFile ~/.ssh/termstead-lab

Host nat-gw
  HostName middle
  Port 22
  User lab
  IdentityFile ~/.ssh/termstead-lab

Host 10.0.2.5
  HostName app
  Port 22
  User lab
  IdentityFile ~/.ssh/termstead-lab
  RequestTTY force
  RemoteCommand sh /tmp/demo/db.sh

Host 10.0.1.13
  HostName db
  Port 22
  User lab
  IdentityFile ~/.ssh/termstead-lab
  RequestTTY force
  RemoteCommand sh /tmp/demo/web02.sh

Host *
